repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.14.1
  hooks:
    # Run the linter.
    - id: ruff-check
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format

- repo: https://github.com/facebook/pyrefly-pre-commit
  rev: 0.0.1
  hooks:
    - id: pyrefly-typecheck-system
      name: Pyrefly (type checking)
      pass_filenames: false