name: Ruff
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Ruff
        uses: astral-sh/ruff-action@v3.5.1
        with:
          version: "0.11.13"
          args: check --fix .
